#!/bin/bash
touch `pwd`/index.html;
> `pwd`/index.html;
cat `pwd`/header | sed -e "s#Date#Generated by: <b>`date +%d-%m-%Y' '%H:%M`</b> <br>Relevant from <b>`date +%d-%m-%Y`</b> to <b>`date -d '+7 days' +%d-%m-%Y`</b>#g" >> `pwd`/index.html;

Location_nums=(`for i in {0..2}; do expr \( \( \( $(date +%W) % 3 \) + $i \) % 3 \) + 1; done`);

for position in {1..3};
do
	Name=$(sed -n ${position}p `pwd`/names);

	location_num=${Location_nums[`expr $position - 1`]};
	Location=$(sed -n ${location_num}p `pwd`/locations);

	cat `pwd`/table | sed -e "s/Name/${Name}/g" | sed -e "s/Location/${Location}/g" >> `pwd`/index.html;
done;

cat `pwd`/footer >> `pwd`/index.html;
